#' Helper function for obtaining empirical p-values from the permutation test.
#'
#' @param obsValue The observed value (either a beta coefficient or its corresponding t value).
#' @param nullValues A vector of null values (either beta coefficients or the corresponding t values) generated by the permutation test.
#' @param effectType The type of effect of experimental condition on differential binding to look for, or how the p-value will be computed. Options include \code{"negative"} (p-value is proportion of null effects <= observed effect), \code{"positive"} (p-value is proportion of null effects >= observed effect), or \code{"two-sided"} (p-value is proportion of null effects in absolute value >= observed effect in absolute value). The option chosen here should correspond with how the lower and upper thresholds are chosen in \code{\link{getRegions}}.
#' @param ignoreNAs If \code{TRUE}, p-values will be calculated ignoring any NAs and NaNs among the null values. If \code{FALSE} (the default), NAs will be returned for every p-value if NAs or NaNs are present.
#'
#' @export
#'
findPermPValue <- function(obsValue, nullValues, effectType = "two-sided", ignoreNAs = F){
  if(!(effectType %in% c("negative", "positive", "two-sided"))){
    stop("type of effect (effectType) must be 'negative', 'positive', or 'two-sided'.")
  }

  if(ignoreNAs){
    missing <- which(is.na(nullValues) | is.nan(nullValues))
    #message("Ignoring", length(missing), "NA or NaNs null values.")
    if(length(missing) > 0){
      nullValues <- nullValues[-missing]
    }
  }

  #Account for whether or not the effect is one-sided (options: negative, positive) or two-sided.
  if(effectType=="negative"){
    return(sum(nullValues <= obsValue)/length(nullValues))
  }
  else if(effectType=="positive"){
    return(sum(nullValues >= obsValue)/length(nullValues))
  }

  #two-sided p-value
  return(sum(abs(nullValues) >= abs(obsValue))/length(nullValues))
}
